---
- name: Install Operators on Kubernetes Cluster
  hosts: localhost
  collections:
   - community.kubernetes
  tasks:

  - name: Create a Subscription for Redis Operator
    k8s:
      state: present
      definition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: my-redis-operator
          namespace: openshift-operators
        spec:
          channel: stable
          name: redis-operator
          source: community-operators
          sourceNamespace: openshift-marketplace
