name: odo-podman-test
on:
  pull_request:
    branches:    
      - main
    paths-ignore:
      - 'docs/**'
      - CONTRIBUTING.md
      - OWNERS
      - README.md
      - USAGE_DATA.md

jobs:
  ODO-PODMAN-TEST:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build odo
      run: make install

    - name: Run Integration tests
      env:
        # This should ideally be a configuration in the GH repo (secret or variable).
        # This is currently hard-coded because GH won't expose secrets or variables to PRs created from forks.
        # Hopefully, variables (which are non-sensible by definition) will be passed to workflows triggered by PRs from forks.
        # See https://github.com/community/community/discussions/44322
        PODMAN_EXEC_NODES: 10
      run: make test-integration-podman

    - name: List and stop remaining containers
      if: ${{ always() }}
      run: |
        podman pod ls --format '{{.Name}}' | xargs -I '{}' podman pod inspect '{}'
        podman pod ls --format '{{.Name}}' | xargs podman pod stop || true
